### ISSUE TITLE
Subtitle tracks prevent saving.

### ISSUE THREAD

**Issue by reinstallgentoo** [Sagnac/streamsave#10] opened 2023-11-19 14:04 UTC
Hi, after much troubleshooting I've discovered that subtitle tracks prevent saving, causing the 
"Cache dumping stopped due to an error" msg. Could streamsave ignore subtitle tracks, so toggling them off is not required every time? Thank you

**Comment by Sagnac** [comment] 2023-11-19 19:56
I can't seem to reproduce the error, either with online videos or local ones, although if I remember correctly I think I may have run into it before; I've just tested with a variety of formats and subtitles and have no problem saving the cache. The follow information would be helpful:
* mpv version
* type of stream
* format you're writing to
* type of subtitles
* does toggling off subtitles, writing out continuously, and then toggling them back on while cache saving is in progress cause an error?

as long as it's reproducible I can add a simple workaround

**Comment by Sagnac** [comment] 2023-11-20 06:02
I think I've settled on an appropriate solution. I've tested `.ts` and `.mkv` ouputs with and without internal subs and I don't see the issue with these combinations.  If you can confirm this only happens with MP4 output and internal subs and [this version](../raw/dev/streamsave.lua) of the script works for you then I'll go ahead and merge it. If this issue occurs with other combinations then I'll add the option instead.

**Comment by Sagnac** [comment] 2023-11-20 12:09
So this also happens with WebM if the subs are internal and not WebVTT. I think I've covered all cases now.

**Comment by reinstallgentoo** [comment] 2023-11-21 16:47
I just deleted `force_extension=.mkv` from `streamsave.conf` and I'm now able to write youtube.mkv & youtube264.mkv with the dev branch, however the subtitles are missing (fine with me). Meanwhile it errors with version 2022-7-22

**Comment by Sagnac** [comment] 2023-11-21 17:22
Hmm, what error do you get? From my testing choosing mkv as output is the most flexible and even includes the subs.

with `force_extension=no` youtube.mkv should write to webm and it shouldn't have an issue with webvtt subtitles. The workaround commit excludes this case so there shouldn't be a difference v0.24.1 and v0.25.0

youtube-h264.mkv should choose mp4 by default which will error without the workaround, that one makes sense.

what I'm confused about is why `force_extension=.mkv` should error and why there's a difference between the dev branch and the master branch for webm output with webvtt subtitles

**Comment by reinstallgentoo** [comment] 2023-11-21 17:57
It's the usual "Cache dumping stopped due to an error"
I favour mkv, but I just deleted that line on a whim after posting.

> with force_extension=no youtube.mkv should write to webm and it shouldn't have an issue with webvtt subtitles. The workaround commit excludes this case so there shouldn't be a difference v0.24.1 and v0.25.0
>
>youtube-h264.mkv should choose mp4 by default which will error without the workaround, that one makes sense.

They do write to webm/mp4 respectively, but the webvtt subtitles are missing.
Somehow with `force_extension=.mkv` the youtube-sourced files fail to write with webvtt subtitles enabled.

**Comment by reinstallgentoo** [comment] 2023-11-21 19:32
Is there a log? I've only ever had the same error message.

> If you disable the subtitles those particular files will write correctly with force_extension=.mkv right?

Yes

> To be certain if you delete the force_extension line youtube.mkv fails on master but writes with the dev version? The output is webm for both, right? 

dev
`force_extension=.mkv` deleted
subs enabled
result: success. webm written (without subs)

master
`force_extension=.mkv` deleted
subs enabled
result: error. empty webm written

**Comment by Sagnac** [comment] 2023-11-21 20:35
`--msg-level` in mpv sets how verbose printed console messages are; these types of more specific error messages should show in the terminal on the default of `status` and if you're getting any error messages they should show unless you've raised the log level for that specific module; usually the module for these types of errors is `ffmpeg` or `recorder`. You can also output a log with `--log-file`.

For this youtube.mkv file what does mpv detect the subtitle type as in the console? Your metadata says they're webvtt subs, but I'm thinking mpv is detecting this differently because it's the only way I can think of the workaround would fire; in other words the file is working when it's not supposed to. If you query the `current-tracks/sub/codec` property it should show it; you can run mpv with something like
```
--osd-msg1=${current-tracks/sub/codec}
```
 Do you get the streamsave warning message about incompatible subtitles when it works?

**Comment by reinstallgentoo** [comment] 2023-11-21 21:55
> ..
> [streamsave] .webm output format is incompatible with internal subtitles being selected.
> [streamsave] Subs will be disabled while writing and enabled again when finished.
> Track switched:
>  (+) Video --vid=1 (*) (vp9 1920x1080 50.000fps)
>  (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
>      Subs  --sid=1 --slang=eng 'English' (webvtt-webm)
> Cache dumping started.
> [recorder] This is an experimental feature. Output files might be broken or not play correctly with various
> players (including mpv itself).
> [recorder] Source stream misses DTS on at least some packets!
> [recorder] If the target file format requires DTS, the written file will be invalid.
> [recorder] Discontinuity at timestamp 0.000000.
> [ffmpeg] webm: Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
> Cache dumping successfully ended.
> ..

> --osd-msg1=${current-tracks/sub/codec}

webvtt-webm

Well I don't see what more can be done. The dev branch achieves clipping without disabling subs, and I'm reluctant to push others into chasing edge cases. Thank you for the script and your support

**Comment by Sagnac** [comment] 2023-11-21 22:27
> webvtt-webm

Oh that's interesting, apparently there are two codecs, `webvtt` _and_ `webvtt-webm` and it's the latter which seems to cause problems with mkv. The reason the workaround works is because it's not `webvtt` specifically.

So I guess that tells us this `webvtt-webm` shouldn't ever work, since it doesn't even work with WebM. All that needs to be done is to check against that and the MKV outputs should work too. I'll push a commit addressing this in a while. Out of curiosity, what's the log message when it _does_ fail (youtube.mkv on master branch without force_extension)?

**Comment by Sagnac** [comment] 2023-11-22 00:02
I've updated the `dev` branch with the fix, if that version works for you (especially when writing to MKV) I'll go ahead and merge it. Feel free to report if there any other issues with this, I'll add the toggle option if there are; that way we'll have a baseline workaround for known incompatibilities and a way to guarantee writes when the user doesn't care about subtitles.

At the moment _if_ these `webvtt-webm` subtitles _do_ work with some outputs (for whatever reason) then there's no way to include them; not a big deal, but if this isn't as straightforward as the three internal subtitle cases we're looking at now (mp4 universally, non-webvtt in webm, and webvtt-webm universally) then the option is preferable as a direct alternative.

**Comment by reinstallgentoo** [comment] 2023-11-23 16:34
> what's the log message when it does fail (youtube.mkv on master branch without force_extension)?

```
[cplayer] Cache dumping started.
[recorder] Can't mux one of the input streams.
[cplayer] Cache dumping stopped due to error.
[streamsave] error running command
[statusline] (Paused) AV: 00:00:30.007 / 00:52:44.181 (1%) A-V:  0.000
[streamsave] Possibly broken file created at:./youtube.mkv-[00.00.00 - 00.00.30]-2.webm
```

Here's my yt-dlp config if you'd like to test `webvtt-webm` further.

```
-f "bv*[ext=webm]+ba[ext=webm]/b[ext=webm] / bv*+ba/b"
--merge-output-format mkv
--embed-chapters
--embed-subs
--sub-langs "en.*"
--no-write-auto-subs
```

> I've updated the dev branch with the fix

dev seems good, it's writing regardless of whether the extension is forced or not. Thanks again for working on this, my initial post was poor and I couldn't predict that ffmpeg and mpv would report the subtitle format differently.

**Comment by Sagnac** [comment] 2023-11-23 20:28
> --embed-subs
> I couldn't predict that ffmpeg and mpv would report the subtitle format differently

Yeah, I had no idea either. There's two different WebVTT formats apparently even when both are internal subtitles; it appears you can mux the VTT in a different way when you embed them, I think that's what [this page](http://wiki.webmproject.org/webm-metadata/temporal-metadata/webvtt-in-webm) is talking about. If I  create a.vtt file and mux it into an mkv it'll differ from how yt-dlp is embedding them and mpv has issues with this latter form.

Anyway, if you experience any more issues with this let me know as I have a local branch rebased on top of `dev` which adds a three-valued `toggle_subs=<yes|no|auto>` option which can easily be merged. I'd prefer not to add that complexity unless necessary (as long as our current workaround works universally), but if any issues with internal subtitles persist I think this option is the best approach going forward and should iron things out.

Thanks for reporting the issue.

**Closed** 2023-11-23 20:27 UTC
